import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Container from "./components/container";
import Layout from "./components/layout";
import { StoreContextProvider } from "./context/StoreContext";
import localfont from 'next/font/local';
const myFont=localfont({src:'../../public/fonts//Yekan.woff'})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "فروشگاه ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
       <body
        className={myFont.className}
      >
        <StoreContextProvider>
          <Layout>{children}</Layout>
        </StoreContextProvider>
      </body>
    </html>
  );
}
